# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k325tffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Project/verilog_pro/softmax/prj1/softmax/softmax.cache/wt [current_project]
set_property parent.project_path D:/Project/verilog_pro/softmax/prj1/softmax/softmax.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
add_files D:/Project/verilog_pro/softmax/rtl/rom/rom.coe
read_verilog -library xil_defaultlib {
  D:/Project/verilog_pro/softmax/rtl/addrtodata.v
  D:/Project/verilog_pro/softmax/rtl/getaddr.v
  D:/Project/verilog_pro/softmax/rtl/getf.v
  D:/Project/verilog_pro/softmax/rtl/gety.v
  D:/Project/verilog_pro/softmax/rtl/softmax.v
}
read_ip -quiet D:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/floating_point_0/floating_point_0.xci
set_property used_in_implementation false [get_files -all d:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/floating_point_0/floating_point_0_ooc.xdc]

read_ip -quiet D:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/floating_point_1/floating_point_1.xci
set_property used_in_implementation false [get_files -all d:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/floating_point_1/floating_point_1_ooc.xdc]

read_ip -quiet D:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/divide/divide.xci
set_property used_in_implementation false [get_files -all d:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/divide/divide_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/constrs_1/new/mm.xdc
set_property used_in_implementation false [get_files D:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/constrs_1/new/mm.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top softmax -part xc7k325tffg900-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef softmax.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file softmax_utilization_synth.rpt -pb softmax_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
