# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/divide/divide.xci
# IP: The module: 'divide' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/divide/divide_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divide'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/divide/divide.xci
# IP: The module: 'divide' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/verilog_pro/softmax/prj1/softmax/softmax.srcs/sources_1/ip/divide/divide_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'divide'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
